apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-redis
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data/db
