apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-label
  template:
    metadata:
      labels:
        app: myapp-label
    spec:
      containers:
      - name: myapp
        image: redis:5.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
